# manylinux2014-aarch64 is based on manylinux2014-x64 and the aarch64 toolchain installed. This allows to
# run the container on a x86_64 host.
# This image is not based on "pypa/manylinux2014_aarch64" because it would require the host to be aarch64.
# For more details, read https://github.com/dockcross/dockcross/issues/367
FROM dockcross/manylinux2014-x64:latest

RUN rm -rf /opt/python /opt/_internal

# Provide Python builds for aarch64 to build against
COPY --from=quay.io/pypa/manylinux2014_aarch64:latest /opt/_internal /opt/_internal
COPY --from=quay.io/pypa/manylinux2014_aarch64:latest /opt/python /opt/python

# Libraries needed to run python3 with qemu
RUN mkdir -p /usr/local/aarch64/lib
COPY --from=quay.io/pypa/manylinux2014_aarch64:latest /lib/ld-linux-aarch64.so.1 /lib/
COPY --from=quay.io/pypa/manylinux2014_aarch64:latest /lib64/ /usr/local/aarch64/lib/
COPY --from=quay.io/pypa/manylinux2014_aarch64:latest /usr/local/lib/ /usr/local/aarch64/lib/

# The cross-compiling emulator
RUN \
  yum -y update && \
  yum -y install \
    qemu-user \
    qemu-system-arm && \
    yum clean all

# Makes the manylinux2014_aarch64 libraries available
COPY manylinux2014-aarch64/qemu-aarch64-wrapper.sh /usr/local/bin/
# Script from
# https://github.com/qemu/qemu/blob/master/scripts/qemu-binfmt-conf.sh
# Used to register the wrapper in the Linux kernel to automatically run aarch64
# binaries with the QEMU User emulator.
# docker must be started with the --privileged flag to run. In dockcross, this
# means passing the `-a "--privileged"` argument to the dockcross script.
# Invoke as `sudo qemu-binfmt-conf.sh --qemu-suffix=-wrapper.sh`
COPY manylinux2014-aarch64/qemu-binfmt-conf.sh /usr/local/bin/

ENV XCC_PREFIX /usr/xcc
ENV CROSS_TRIPLE aarch64-linux-musl
ENV CROSS_ROOT ${XCC_PREFIX}/${CROSS_TRIPLE}-cross

RUN mkdir -p ${XCC_PREFIX}
RUN curl -LO http://musl.cc/${CROSS_TRIPLE}-cross.tgz
RUN tar -C ${XCC_PREFIX} -xvf ${CROSS_TRIPLE}-cross.tgz

ENV AS=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-as \
    AR=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-ar \
    CC=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-gcc \
    CPP=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-cpp \
    CXX=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-g++ \
    LD=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-ld \
    FC=${CROSS_ROOT}/bin/${CROSS_TRIPLE}-gfortran

ENV QEMU_LD_PREFIX "${CROSS_ROOT}/${CROSS_TRIPLE}/sysroot"
ENV QEMU_SET_ENV "LD_LIBRARY_PATH=${CROSS_ROOT}/lib:${QEMU_LD_PREFIX}"

COPY manylinux2014-aarch64/Toolchain.cmake ${CROSS_ROOT}/
ENV CMAKE_TOOLCHAIN_FILE ${CROSS_ROOT}/Toolchain.cmake

ENV PKG_CONFIG_PATH /usr/lib/aarch64-linux-gnu/pkgconfig

# Linux kernel cross compilation variables
ENV PATH ${PATH}:${CROSS_ROOT}/bin
ENV CROSS_COMPILE ${CROSS_TRIPLE}-
ENV ARCH arm64

ENV AUDITWHEEL_ARCH aarch64
ENV AUDITWHEEL_PLAT manylinux2014_$AUDITWHEEL_ARCH

ARG IMAGE=dockcross/manylinux2014-aarch64

#include "common.label-and-env"
