ARG ORG=dockcross
ARG HOST_ARCH=amd64
FROM ${ORG}/web-wasi:latest-${HOST_ARCH}

LABEL maintainer="Matt McCormick matt@mmmccormick.com"

ENV CROSS_TRIPLE=wasm32-wasi-threads

COPY Toolchain.cmake ${CROSS_ROOT}/
ENV CMAKE_TOOLCHAIN_FILE=${CROSS_ROOT}/Toolchain.cmake

#include "common.label-and-env"
